# build only master branch and version tags
branches:
  only:
  - master
  - /^\d*\.\d*\.\d*$/

sudo: required

services:
- docker

language: cpp
dist: xenial
os: linux

addons:
  apt:
    sources:
      - sourceline: 'deb https://dl.bintray.com/igagis/ubu unstable main'
        key_url: 'http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x379CE192D401AB61'
    update: true
    packages:
    - binfmt-support
    - qemu-user-static
    - myci

matrix:
  include:
    - name: macosx
    os: osx
    compiler: clang
    osx_image: xcode8.3


env:
  global:
  #encrypted HOMEBREW_GITHUB_ACCESS_TOKEN for publishing to homebrew-tap
  - secure: "PRL8mGJ6seQnPNeJZ9XwioNGPpRbVf6Lc8dBV1gPvf24/Dc3CnaU17YRzu2J06AfihyN+FC+5mo/mrjpgLjXkVqUVXyK9H5Foivi42eg4NVO8I5yrqSx0ej/xxSTbJMm+Muv31D1Mb/AuL/oIFUxcyRiV7Zzvq6X36LgcAQK8yEhl2XV1Fc84EnVF19DxpdVvHh6hxtaKzBwUAyJVyHv4T+iGa7a2aYJ5h+iH2wdv57cR16D3h6BtGWxJd+MS7BBmQiWNPX6t6sHCcJjLzlZi+zLJsYeVLV6BwJyejh/S55E0zOvIeqINC+qURZzVwpFuO6f1xMrFZCawEPcrMDXT0Z7qHuhbryCzZvUY5iZ3J4wnzIlTYUfRN4sYiSKsWXKReAu7yZ6xrW7ckk89Y2D8CFCYwtiV3Ds7J0FSYji9zEbsNuOsQtHfHr201xkAWltxZpRmw7ljzhDS50N1CjAuZS8CdXbP8rnRlhV1YgBr/uvjZWxqpZQm6yqBbDzPHJN18WzAm//npPuaArAnIAFyd0QhXoId5KPW9eE00EDEuOQ2lad7ryrHwGGG5cStQzq4ypIk4FqxrZmufddw33iz6o4kTe/YzQ07gueGk62cHKrNFCyg9y1cNijmvi9/VsdttQCzuYK8Fy7Ap+Ia684FzDb1gCBbAexngUjQOKV72E="
  - MYCI_GIT_ACCESS_TOKEN=$HOMEBREW_GITHUB_ACCESS_TOKEN
  - MYCI_GIT_USERNAME=igagis
  - USE_ANDROID_NDK_VERSION=15c
  - linuxDependencies="debhelper fakeroot myci"
  - PACKAGE_NAME=prorab
  matrix:
  - OS_REL=xenial OS=ubuntu DOCKER_IMAGE=$OS:$OS_REL PACKAGE_TYPE=deb
  - OS_REL=bionic OS=ubuntu DOCKER_IMAGE=$OS:$OS_REL PACKAGE_TYPE=deb
  - OS_REL=stretch OS=debian DOCKER_IMAGE=$OS:$OS_REL PACKAGE_TYPE=deb
  - OS_REL=stretch OS=raspbian DOCKER_IMAGE=igagis/$OS:$OS_REL PACKAGE_TYPE=deb

before_install:
- if [ "$TRAVIS_OS_NAME" == "linux" ] && [ -z "$TRAVIS_JOB_NAME" ]; then
    docker run --name ccc -v $TRAVIS_BUILD_DIR/..:/build -w /build/$(basename $TRAVIS_BUILD_DIR) -it -d $DOCKER_IMAGE bash &&
    if [ "$PACKAGE_TYPE" == "deb" ]; then
      docker exec ccc bash -c "echo 'deb https://dl.bintray.com/igagis/ubu unstable main' > /etc/apt/sources.list.d/igagis.list" &&
      docker exec ccc apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 379CE192D401AB61 &&
      docker exec ccc apt update &&
      docker exec ccc apt install -y devscripts equivs myci &&
      myci-deb-prepare.sh;
    fi;
  fi
- if [ "$TRAVIS_JOB_NAME" == "macosx" ]; then
    rvm install ruby-2.3.3 &&
    rvm use ruby-2.3.3 &&

    brew update > /dev/null &&
    brew tap igagis/tap &&
    brew update > /dev/null &&
    brew install myci;
  fi

install:
- if [ "$TRAVIS_OS_NAME" == "linux" ] && [ -z "$TRAVIS_JOB_NAME" ]; then
    docker exec ccc myci-deb-install-build-deps.sh;
  fi

script:
- if [ "$TRAVIS_OS_NAME" == "linux" ] && [ -z "$TRAVIS_JOB_NAME" ]; then
    docker exec ccc dpkg-buildpackage -us -uc;
  fi
- if [ "$TRAVIS_JOB_NAME" == "macosx" ]; then
    make test &&
    make install;
  fi

deploy:
- provider: script
  skip_cleanup: true
  on:
    tags: true
    condition: $PACKAGE_TYPE = deb && -z "$TRAVIS_JOB_NAME"
  script: myci-deploy-debian-bintray.sh -u igagis -r $OS -p $PACKAGE_NAME -c main -d $OS_REL $TRAVIS_BUILD_DIR/../*.deb
- provider: script
  skip_cleanup: true
  script: myci-deploy-homebrew.sh -t igagis/tap
  on:
    tags: true
    condition: $TRAVIS_JOB_NAME = macosx
