language: cpp
sudo: required
dist: trusty

os:
  - linux
  - osx

env:
  global:
  - secure: "PRL8mGJ6seQnPNeJZ9XwioNGPpRbVf6Lc8dBV1gPvf24/Dc3CnaU17YRzu2J06AfihyN+FC+5mo/mrjpgLjXkVqUVXyK9H5Foivi42eg4NVO8I5yrqSx0ej/xxSTbJMm+Muv31D1Mb/AuL/oIFUxcyRiV7Zzvq6X36LgcAQK8yEhl2XV1Fc84EnVF19DxpdVvHh6hxtaKzBwUAyJVyHv4T+iGa7a2aYJ5h+iH2wdv57cR16D3h6BtGWxJd+MS7BBmQiWNPX6t6sHCcJjLzlZi+zLJsYeVLV6BwJyejh/S55E0zOvIeqINC+qURZzVwpFuO6f1xMrFZCawEPcrMDXT0Z7qHuhbryCzZvUY5iZ3J4wnzIlTYUfRN4sYiSKsWXKReAu7yZ6xrW7ckk89Y2D8CFCYwtiV3Ds7J0FSYji9zEbsNuOsQtHfHr201xkAWltxZpRmw7ljzhDS50N1CjAuZS8CdXbP8rnRlhV1YgBr/uvjZWxqpZQm6yqBbDzPHJN18WzAm//npPuaArAnIAFyd0QhXoId5KPW9eE00EDEuOQ2lad7ryrHwGGG5cStQzq4ypIk4FqxrZmufddw33iz6o4kTe/YzQ07gueGk62cHKrNFCyg9y1cNijmvi9/VsdttQCzuYK8Fy7Ap+Ia684FzDb1gCBbAexngUjQOKV72E="
  - HOMEBREW_GITHUB_USERNAME=igagis

before_install:
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    sudo apt-get update -qq;
    sudo apt-get install debhelper -qq;
  fi

script:
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    make deb;
  fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    make install;
  fi

deploy:
- provider: bintray
  skip_cleanup: true
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux
  file: travis_bintray.json
  user: igagis
  key:
    secure: lzwel5dBXpkklB4USNwKSjFLTYZ4nYHFVuQUY3PKwfz6srCGVcl8R6ryOn4GD6qUJiwdv+q8lXCnFAP5IwlOdsXKyndgVs4047eQbNUq6nrKHRI9xmIc3IY/h3D68vt+akortZFDxI2mBxQImpWaNML+rlI4Hts13WB5EL18UVZjthZZmViSvo1M/VuYy46NBvw6YIGOIYuM7t/dkewFcnOLrU+KLH9ANRRUoTymiw5jYvXGXEdqG/Lg7bLvm5TutyHqW6P+mSh97T5qAGANsbgeguF77jxmK4dS7GoIeBFKm43Iv6T9KoL+45Z9qe+5L7J3EXacEPEtQBmi5ta7jKnrSnzeeftXkhz5wxNStS988QhgGDeHlW585XfTtAyehjegOI2h3jBmpJDrWJHhxCDHA4H+younQYALtrRfr0paVtaehZ9Ov7q1bBnhVYA8+5BMTQPbIJqCv3nMoGuvHaVnllxGmghXG/cKKN0dMFFY87cxbVxrS0NvXvE6FQf3wl/g+4yazG5IcAj//eq6UOHNlRHT0VG6HDr7l/wJU3kxXHK4lrRo0jWqUsEfR7fmBnv/Nvgn4+p21mAWM63zwXaV+Inx75Tvc0NqnuiKmChGxWf1JcLuXmdc5cQ3LWjx4OrF8Lo8NEDiSulXm7f2rVSTGs5xgyd6T5WcdGSynnA=
  dry-run: false
- provider: script
  skip_cleanup: true
  script: prorab-deploy-homebrew.sh igagis/tap
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = osx
