os: Visual Studio 2015
version: "{branch}-{build}"

clone_folder: c:\projects\build

environment:
  PRORAB_GIT_USERNAME: igagis
  PRORAB_GIT_ACCESS_TOKEN:
    secure: mpW6B2ols1a2FkshjKjryBuvBt8A1TpU9WGn+/d6PIQiZlzA0Rpo1ETKpmy0bnvX
  DEPS: make,cygport,gcc-g++

install:
  - cmd: C:\cygwin64\setup-x86_64.exe -q -P lynx,wget,%DEPS%
  - cmd: C:\cygwin\setup-x86.exe -q -P lynx,wget,%DEPS%
  - cmd: xcopy /S C:\projects\build C:\cygwin64\home\appveyor\
  - cmd: xcopy /S C:\projects\build C:\cygwin\home\appveyor\

before_build:

build_script:
  - cmd: C:\cygwin64\bin\bash -e -l -c "./src/prorab-apply-version.sh -v `./src/prorab-deb-version.sh debian/changelog` cygwin/*.in"
  - cmd: C:\cygwin64\bin\bash -e -l -c "cygport cygwin/*.cygport download"
  - cmd: C:\cygwin64\bin\bash -e -l -c "cygport cygwin/*.cygport all"
  - cmd: C:\cygwin\bin\bash -e -l -c "./src/prorab-apply-version.sh -v `./src/prorab-deb-version.sh debian/changelog` cygwin/*.in"
  - cmd: C:\cygwin\bin\bash -e -l -c "cygport cygwin/*.cygport download"
  - cmd: C:\cygwin\bin\bash -e -l -c "cygport cygwin/*.cygport all"

test_script:
  - cmd: C:\cygwin64\bin\bash -e -l -c "PATH=$PATH:~/src make test"
  - cmd: C:\cygwin\bin\bash -e -l -c "PATH=$PATH:~/src make test"

deploy_script:
  - cmd: C:\cygwin64\bin\bash -e -l -c "make install"
  - cmd: C:\cygwin\bin\bash -e -l -c "make install"
  - cmd: C:\cygwin64\bin\bash -e -l -c "prorab-deploy-cygwin.sh -r igagis/cygwin-repo"
  - cmd: C:\cygwin\bin\bash -e -l -c "prorab-deploy-cygwin.sh -r igagis/cygwin-repo"
