os: Visual Studio 2015
version: "{branch}-{build}"

clone_folder: c:\projects\build

environment:
  DEPS: make cygport

install:
  - cmd: C:\cygwin64\setup-x86_64.exe -q -P lynx,wget
  - cmd: C:\cygwin\setup-x86.exe -q -P lynx,wget
  - ps: (new-object net.webclient).DownloadFile('https://raw.githubusercontent.com/transcode-open/apt-cyg/master/apt-cyg', 'C:\cygwin64\bin\apt-cyg')
  - cmd: copy C:\cygwin64\bin\apt-cyg C:\cygwin\bin\apt-cyg
  - cmd: C:\cygwin64\bin\bash -e -l -c "chmod +x /bin/apt-cyg"
  - cmd: C:\cygwin\bin\bash -e -l -c "chmod +x /bin/apt-cyg"
  - cmd: C:\cygwin64\bin\bash -e -l -c "apt-cyg install %DEPS%"
  - cmd: C:\cygwin\bin\bash -e -l -c "apt-cyg install %DEPS%"
  - cmd: xcopy /S C:\projects\build C:\cygwin64\home\appveyor\
  - cmd: xcopy /S C:\projects\build C:\cygwin\home\appveyor\

before_build:
#  - nuget restore msvs_solution/msvs_solution.sln

build_script:
  - cmd: C:\cygwin64\bin\bash -e -l -c "ls && cd build && ./src/prorab-apply-version.sh -v `./src/prorab-deb-version.sh debian/changelog` cygwin/*.in"
  - cmd: C:\cygwin64\bin\bash -e -l -c "cd build && cygport cygwin/*.cygport download"
  - cmd: C:\cygwin64\bin\bash -e -l -c "cd build && cygport cygwin/*.cygport all"

test_script:
  - cmd: C:\cygwin64\bin\bash -e -l -c "cd build && make test"
#  - ps: .\tests\autotest-appveyor.ps1

#deploy:
#  provider: NuGet
#  api_key:
#    secure: cvBwlGzXt2fwZB1AFv+aJZca9hCQf4hW/BYwKOjCjCx0WFD9L6g9e2IH7SZ+P0Qf
#  skip_symbols: true
#  artifact: /.*\.nupkg/
#  on:
#    appveyor_repo_tag: true
#
#artifacts:
#  - path: .\nuget\*.nupkg
